set nocompatible               " Prevent vim from using legacy vi behavior as defaults
set tabstop=4                  " Make tabs as wide as 4 spaces
set shiftwidth=4               " Make >> and << shift text to match tab width
set expandtab                  " Insert spaces when <TAB> is pressed
" (You can use <CTRL-V><TAB> in insert mode to insert a TAB character if you need to.)

set ruler                      " Add line and column numbers at bottom of screen
set backspace=indent,eol,start " Make backspace not stop for anything
syntax on                      " Turn on syntax highlighting

" Make backspace delete preceding character in normal mode
nmap <BS> X
