#!/bin/sh

PATH=/sbin:/bin:/usr/bin

test -f /home/root/rascal/bin/paster || exit 0

BASE_DIR="/home/root/helloworld"
PASTER_CONFIG="/home/root/helloworld/development.ini"
test -f $PASTER_CONFIG || exit 0

cd $BASE_DIR

case "$1" in
start)
  echo "Starting Rascal webserver..."
  /home/root/rascal/bin/paster serve --daemon $PASTER_CONFIG start
  echo "done"
  ;;
restart)
  echo "Restarting Rascal webserver..."
  /home/root/rascal/bin/paster serve --daemon $PASTER_CONFIG restart
  echo "done"
  ;;
stop)
  echo "Stopping Rascal webserver..."
  /home/root/rascal/bin/paster serve --daemon $PASTER_CONFIG stop
  echo "done"
  ;;
*)
  echo "Bad argument supplied to rascal-webserver script."
  echo "Usage: /etc/init.d/rascal-webserver {start|stop|restart}"
  exit 1
esac

exit 0
